name: ailoitte_assessment
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  provider: ^6.0.2
  shared_preferences: ^2.0.13
  flutter_native_splash: ^2.1.6
  double_back_to_close_app: ^2.1.0

dev_dependencies:
  flutter_lints: ^1.0.4

flutter:
  uses-material-design: true